### ISSUE TITLE
Issue: Todo App

### ISSUE THREAD

**Issue by junho01052** [junho01052/Todo-App#1]
### 만들고자 하는 기능이 무엇인가요?
- TODO 생성기능

### 해당 기능을 구현하기 위해 해야할 일은 무엇인가요?
1. [x] git repository 생성 후 README, gitignore, LICENSE 파일 생성
2. [x] issue와 milestone 생성 후 칸반 뷰로 변경
3. [x] main, dev 브랜치 생성 후 dev브랜치에서 main 브랜치로 Pull Request 시도
4. [x] Create-react-app 적용 후 Redux, Styled-Component, ESLint, Prettier 설치
5. [x] npm run start가 에러없이 시작하는 코드를 main 브랜치로 push
6. [x] 브라우저 화면 캡쳐 후 제출
